spring:
  profiles:
    active:
      - dev
---

server:
  port: 8080
  ssl:
    enabled: false

spring:
  config:
    activate:
      on-profile:
        - dev

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.230.85.51:1771:digilend
    username: digilend_app
    password: Digilend#123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

#springdoc:
#  swagger-ui:
#    path: /digital-lending-apidocs.html




  #Liquibase properties#
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  #ESB Properties
esb:
  existing-customer-individual-endpoint :
    uri: http://10.235.66.96:7809/ntbservicesapi/v1/ExistingCustomerIndividualInquiry
  customer-information-endpoint :
    uri: http://10.235.66.96:7800/accountservicesapi/v1/AccountServices
  existing-rsme-endpoint :
    uri: http://10.235.66.95:8800/id/mbi/v1/SME_DL/CheckExstRSMECust
  connection-timeout: 2000

---

server:
  port: 8081
  ssl:
    enabled: false

spring:
  config:
    activate:
      on-profile:
        - uat

  datasource:
    driver-class-name:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

server:
  port: 8082
  ssl:
    enabled: false

spring:
  config:
    activate:
      on-profile:
        - prod

  datasource:
    driver-class-name:
    url:
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
