package id.co.maybank.digitallending.model;

import id.co.maybank.digitallending.base.BaseModel;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.time.LocalDate;

/**
 * Let's create entity class for generate table to schema database with the name (table : individual_identify) and we
 * use snake case for naming format
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Entity
@Table(name = "individual_identity")
public class IndividualIdentity extends BaseModel implements Serializable {

	/**
	 * @author muhammadmufqi - Digital Non Retail Division - IT Digital Delivery & Operation, PT Bank Maybank Indonesia Tbk
	 * @version 1.0
	 * @since 1.0 (Created June. 13, 2023)
	 */

	/**
	 * Using @{@link Serializable} that object can save to memory
	 */
	private static final long serialVersionUID = 2347068152537690558L;

	/**
	 * The column name is not filled in (details the name of table), so that it is generated by JPA. This is because the
	 * naming column from ERD conforms to the Java naming standard. (Standard naming java and naming ERD (Documentation)
	 * are match) We use snake case for the naming to database
	 */
	@Id
	@Column(length = 16)
	private Long nik;

	@NotNull
	@Column(length = 160)
	private String name;

	@NotNull
	private LocalDate dateOfBirth;

	@NotNull
	@Column(length = 100)
	private String email;

	@NotNull
	@Column(length = 3)
	private String category;
}
